import { Link } from 'react-router-dom';
import { NewsletterForm } from './NewsletterForm';

const COLUMNS = [
  { title: 'Shop', links: [{ to: '/shop', label: 'All wigs' }, { to: '/shop?category=bundles', label: 'Bundles' }, { to: '/shop?category=serum', label: 'Hair care' }] },
  { title: 'NNE', links: [{ to: '/about', label: 'Our story' }, { to: '/contact', label: 'Book an install' }, { to: '/faq', label: 'Care guide' }] },
  { title: 'Support', links: [{ to: '/shipping-policy', label: 'Delivery' }, { to: '/returns-policy', label: 'Returns' }, { to: '/privacy-policy', label: 'Privacy' }] },
];

export function Footer() {
  return <footer className="mt-24 border-t border-[#ead6da] bg-[#fdf2f4]"><div className="shell py-16 lg:py-20"><div className="grid gap-12 lg:grid-cols-12 lg:gap-8"><div className="lg:col-span-5"><p className="font-display text-[35px] tracking-[0.12em] text-[#251d20]">NNE</p><p className="mt-1 text-[10px] uppercase tracking-luxe text-[#a7627a]">Luxe Hair</p><p className="mt-4 max-w-xs font-display text-xl italic text-[#745a62]">Beauty in every strand.</p><div className="mt-8 max-w-sm"><p className="text-[13px] font-medium text-[#251d20]">Join the NNE girls.</p><p className="mt-1.5 text-[13px] leading-relaxed text-[#8b7077]">New drops, care tips, and appointment openings. Straight to your inbox.</p><NewsletterForm source="footer" className="mt-4" /></div></div><div className="grid grid-cols-2 gap-8 sm:grid-cols-3 lg:col-span-6 lg:col-start-7">{COLUMNS.map((column) => <nav key={column.title} aria-label={column.title}><h2 className="eyebrow mb-4 text-[#9a536b]">{column.title}</h2><ul className="-my-1 space-y-0.5 sm:space-y-1">{column.links.map((link) => <li key={link.to + link.label}><Link to={link.to} className="inline-flex min-h-[40px] items-center text-[13.5px] text-[#8b7077] transition-colors hover:text-[#251d20] lg:min-h-0 lg:py-1">{link.label}</Link></li>)}</ul></nav>)}</div></div><div className="mt-14 flex flex-col gap-6 border-t border-[#e7cbd2] pt-8 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-5"><a href="https://www.tiktok.com/@nneluxehair" target="_blank" rel="noreferrer" className="flex min-h-[44px] items-center gap-2 text-[12.5px] text-[#8b7077] hover:text-[#251d20]">TikTok ↗</a><a href="https://wa.me/2349028774078" target="_blank" rel="noreferrer" className="flex min-h-[44px] items-center gap-2 text-[12.5px] text-[#8b7077] hover:text-[#251d20]">WhatsApp ↗</a></div><p className="text-[12px] text-[#af8e98]">© {new Date().getFullYear()} NNE Luxe Hair. All rights reserved.</p></div><p className="mt-6 max-w-3xl text-[11.5px] leading-relaxed text-[#af8e98]">Hair colour, texture, availability, delivery times, and final pricing vary by unit. Please confirm details with NNE Luxe Hair before placing an order.</p></div></footer>;
}
